# Generated by Django 4.0.1 on 2022-02-06 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_trainee2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trainee_name', models.CharField(max_length=10)),
                ('faculty', models.CharField(max_length=16)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.track')),
            ],
        ),
    ]
